### ISSUE TITLE
PrideXmlReader.getSourceFile() broken

### ISSUE THREAD

**Issue by julianu** [PRIDE-Utilities/pride-jaxb#1]
PrideXmlReader.getSourceFile() should return the <sourceFile> tag of the PRIDE XML file.
But it returns a File object, ponting to the actual PRIDE XML file.

**Comment by ypriverol** [comment]
What do you mean by tag?

**Comment by julianu** [comment]
Sorry, element of the PRDE XML file, like this:

```
    <sourceFile>
      <nameOfFile>F016532.dat</nameOfFile>
      <pathToFile>E:\Vinni\Pride\Dat files\Proteomics\Mouse\Xenografts\F016532.dat</pathToFile>
      <fileType>Mascot dat file</fileType>
    </sourceFile>
```

**Comment by julianu** [comment]
Just figured out: it is in the admin section.
